doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    'DoctrineMigrations': '%kernel.project_dir%/migrations'

  enable_profiler: '%kernel.debug%'

  custom_template: "%kernel.project_dir%/migrations/migration.tpl"

  storage:
    table_storage:
      table_name: 'migration_versions'

  # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
  organize_migrations: BY_YEAR_AND_MONTH
