# https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
app_stimulus:
  path: /stimulus
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    template: static/stimulus.html.twig